<?php

namespace IntoPeople\DatabaseBundle\Entity;

/**
 * CdptemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CdptemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNewest($organization) {
                   
        $query = $this->createQueryBuilder('c')
            ->where('c.organization = :organization')
            ->setParameter('organization', $organization)
            ->orderBy('c.date', 'DESC')
            ->getQuery();
        
        return $query->setMaxResults(1)->getOneOrNullResult();
               
    }
    
    public function findAllStandardtemplates() {
        
        $query = $this->createQueryBuilder('c')
        ->where('c.isstandardtemplate = :template')
        ->setParameter('template', 1)
        ->getQuery();
        
        return $query->getResult();
        
    }
}
