<?php

namespace IntoPeople\DatabaseBundle\Entity;

/**
 * EndyeartemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndyeartemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNewest($organization) {
         
        $query = $this->createQueryBuilder('e')
        ->where('e.organization = :organization')
        ->setParameter('organization', $organization)
        ->orderBy('e.date', 'DESC')
        ->getQuery();
    
        return $query->setMaxResults(1)->getOneOrNullResult();
         
    }
    
}
