<?php

namespace IntoPeople\DatabaseBundle\Entity;

/**
 * FeedbackcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackcycleRepository extends \Doctrine\ORM\EntityRepository
{
       
    
}
