<?php

namespace IntoPeople\DatabaseBundle\Entity;

/**
 * MidyeartemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MidyeartemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNewest($organization) {
         
        $query = $this->createQueryBuilder('m')
        ->where('m.organization = :organization')
        ->setParameter('organization', $organization)
        ->orderBy('m.date', 'DESC')
        ->getQuery();
    
        return $query->setMaxResults(1)->getOneOrNullResult();
         
    }
    
}
