corequality:
    path:     /
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:index" }

corequality_show:
    path:     /{id}/show
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:show" }

corequality_new:
    path:     /new
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:new" }

corequality_create:
    path:     /create
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:create" }
    methods:  POST

corequality_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:edit" }

corequality_update:
    path:     /{id}/update
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:update" }
    methods:  [POST, PUT]

corequality_delete:
    path:     /{id}/delete
    defaults: { _controller: "IntoPeopleDatabaseBundle:Corequality:delete" }
    methods:  [POST, DELETE]
