endyeartemplate:
    path:     /
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:index" }

endyeartemplate_show:
    path:     /{id}/show
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:show" }

endyeartemplate_new:
    path:     /new
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:new" }

endyeartemplate_create:
    path:     /create
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:create" }
    methods:  POST

endyeartemplate_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:edit" }

endyeartemplate_update:
    path:     /{id}/update
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:update" }
    methods:  [POST, PUT]

endyeartemplate_delete:
    path:     /{id}/delete
    defaults: { _controller: "IntoPeopleDatabaseBundle:Endyeartemplate:delete" }
    methods:  [POST, DELETE]
