endyear_update:
    path:     /{id}/update
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyEndyear:update" }
    methods:  [POST, PUT]
    
endyear_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyEndyear:edit" }
    options:
      expose: true
    
endyear_show:
    path:     /{id}/show
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyEndyear:show" }