midyeartemplate:
    path:     /
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:index" }

midyeartemplate_show:
    path:     /{id}/show
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:show" }

midyeartemplate_new:
    path:     /new
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:new" }

midyeartemplate_create:
    path:     /create
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:create" }
    methods:  POST

midyeartemplate_edit:
    path:     /{id}/edit
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:edit" }

midyeartemplate_update:
    path:     /{id}/update
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:update" }
    methods:  [POST, PUT]

midyeartemplate_delete:
    path:     /{id}/delete
    defaults: { _controller: "IntoPeopleDatabaseBundle:Midyeartemplate:delete" }
    methods:  [POST, DELETE]
