midyear_update:
    path:     /{id}/update
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyMidyear:update" }
    methods:  [POST, PUT]
    
midyear_edit:
    path:     /{id}/{languageId}/edit
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyMidyear:edit" }
    options:
      expose: true

midyear_show:
    path:     /{id}/show
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyMidyear:show" }

midyear_language:
    path:     /{id}/language
    defaults: { _controller: "IntoPeopleDatabaseBundle:MyMidyear:language" }