into_people_database_profile_show:
    path: /
    #defaults: { _controller: "FOSUserBundle:Profile:show" }
    defaults: { _controller: "IntoPeopleDatabaseBundle:User:profile" }
    methods: "GET"

into_people_database_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }
