
into_people_admin_profile_show:
    path: /
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    methods: "GET"

into_people_admin_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }
